

def noun_masc(lemma):
    forms = {}
    forms[lemma] = [lemma, "NOUN", "masc", "sing", "nom"]
    if lemma[-1] in "ाआ":
        forms[lemma[:-1] + "े"] = [lemma, "NOUN", "masc", "plur", "nom"]
        forms[lemma + "ला"] = [lemma, "NOUN", "masc", "sing", "acc"]
        forms[lemma + "ंना"] = [lemma, "NOUN", "masc", "plur", "acc"]
        forms[lemma + "नें"] = [lemma, "NOUN", "masc", "sing", "inst"]
        forms[lemma + "ंनीं"] = [lemma, "NOUN", "masc", "plur", "inst"]
        forms[lemma + "ला"] = [lemma, "NOUN", "masc", "sing", "dat"]
        forms[lemma + "ंना"] = [lemma, "NOUN", "masc", "plur", "dat"]
        forms[lemma + "हून"] = [lemma, "NOUN", "masc", "sing", "abl"]
        forms[lemma + "ंहून"] = [lemma, "NOUN", "masc", "plur", "abl"]
        forms[lemma + "चा"] = [lemma, "NOUN", "masc", "sing", "gen"]
        forms[lemma + "ंचा"] = [lemma, "NOUN", "masc", "plur", "gen"]
        forms[lemma + "त"] = [lemma, "NOUN", "masc", "sing", "loc"]
        forms[lemma + "त"] = [lemma, "NOUN", "masc", "plur", "loc"]
        forms[lemma] = [lemma, "NOUN", "masc", "sing", "voc"]
        forms[lemma + "ंनों"] = [lemma, "NOUN", "masc", "plur", "voc"]
    else:
        forms[lemma] = [lemma, "NOUN", "masc", "plur", "nom"]
        forms[lemma + "ाला"] = [lemma, "NOUN", "masc", "sing", "acc"]
        forms[lemma + "ांना"] = [lemma, "NOUN", "masc", "plur", "acc"]
        forms[lemma + "ानें"] = [lemma, "NOUN", "masc", "sing", "inst"]
        forms[lemma + "ांनीं"] = [lemma, "NOUN", "masc", "plur", "inst"]
        forms[lemma + "ाला"] = [lemma, "NOUN", "masc", "sing", "dat"]
        forms[lemma + "ांना"] = [lemma, "NOUN", "masc", "plur", "dat"]
        forms[lemma + "ाहून"] = [lemma, "NOUN", "masc", "sing", "abl"]
        forms[lemma + "ांहून"] = [lemma, "NOUN", "masc", "plur", "abl"]
        forms[lemma + "ाचा"] = [lemma, "NOUN", "masc", "sing", "gen"]
        forms[lemma + "ांचा"] = [lemma, "NOUN", "masc", "plur", "gen"]
        forms[lemma + "ात"] = [lemma, "NOUN", "masc", "sing", "loc"]
        forms[lemma + "ात"] = [lemma, "NOUN", "masc", "plur", "loc"]
        forms[lemma + "ा"] = [lemma, "NOUN", "masc", "sing", "voc"]
        forms[lemma + "ांनों"] = [lemma, "NOUN", "masc", "plur", "voc"]

    return forms




def noun_fem(lemma):
    forms = {}
    forms[lemma] = [lemma, "NOUN", "fem", "sing", "nom"]
    '''
    if lemma[-1] in "ाआउु":
        forms[lemma[:-1] + "े"] = [lemma, "NOUN", "fem", "plur", "nom"]
        forms[lemma + "ला"] = [lemma, "NOUN", "fem", "sing", "acc"]
        forms[lemma + "ंना"] = [lemma, "NOUN", "fem", "plur", "acc"]
        forms[lemma + "नें"] = [lemma, "NOUN", "fem", "sing", "inst"]
        forms[lemma + "ंनीं"] = [lemma, "NOUN", "fem", "plur", "inst"]
        forms[lemma + "ला"] = [lemma, "NOUN", "fem", "sing", "dat"]
        forms[lemma + "ंना"] = [lemma, "NOUN", "fem", "plur", "dat"]
        forms[lemma + "हून"] = [lemma, "NOUN", "fem", "sing", "abl"]
        forms[lemma + "ंहून"] = [lemma, "NOUN", "fem", "plur", "abl"]
        forms[lemma + "चा"] = [lemma, "NOUN", "fem", "sing", "gen"]
        forms[lemma + "ंचा"] = [lemma, "NOUN", "fem", "plur", "gen"]
        forms[lemma + "त"] = [lemma, "NOUN", "fem", "sing", "loc"]
        forms[lemma + "त"] = [lemma, "NOUN", "fem", "plur", "loc"]
        forms[lemma] = [lemma, "NOUN", "fem", "sing", "voc"]
        forms[lemma + "ंनों"] = [lemma, "NOUN", "fem", "plur", "voc"]
    else:
        forms[lemma + "ी"] = [lemma, "NOUN", "fem", "plur", "nom"]
        forms[lemma + "ीला"] = [lemma, "NOUN", "fem", "sing", "acc"]
        forms[lemma + "ींना"] = [lemma, "NOUN", "fem", "plur", "acc"]
        forms[lemma + "ीनें"] = [lemma, "NOUN", "fem", "sing", "inst"]
        forms[lemma + "ींनीं"] = [lemma, "NOUN", "fem", "plur", "inst"]
        forms[lemma + "ीला"] = [lemma, "NOUN", "fem", "sing", "dat"]
        forms[lemma + "ींना"] = [lemma, "NOUN", "fem", "plur", "dat"]
        forms[lemma + "ीहून"] = [lemma, "NOUN", "fem", "sing", "abl"]
        forms[lemma + "ींहून"] = [lemma, "NOUN", "fem", "plur", "abl"]
        forms[lemma + "ीचा"] = [lemma, "NOUN", "fem", "sing", "gen"]
        forms[lemma + "ींचा"] = [lemma, "NOUN", "fem", "plur", "gen"]
        forms[lemma + "ीत"] = [lemma, "NOUN", "fem", "sing", "loc"]
        forms[lemma + "ींत"] = [lemma, "NOUN", "fem", "plur", "loc"]
        forms[lemma + "ी"] = [lemma, "NOUN", "fem", "sing", "voc"]
        forms[lemma + "ींनों"] = [lemma, "NOUN", "fem", "plur", "voc"]
    '''
    forms[lemma + "ी"] = [lemma, "NOUN", "fem", "plur", "nom"]
    forms[lemma + "ीला"] = [lemma, "NOUN", "fem", "sing", "acc"]
    forms[lemma + "ींना"] = [lemma, "NOUN", "fem", "plur", "acc"]
    forms[lemma + "ीनें"] = [lemma, "NOUN", "fem", "sing", "inst"]
    forms[lemma + "ींनीं"] = [lemma, "NOUN", "fem", "plur", "inst"]
    forms[lemma + "ीला"] = [lemma, "NOUN", "fem", "sing", "dat"]
    forms[lemma + "ींना"] = [lemma, "NOUN", "fem", "plur", "dat"]
    forms[lemma + "ीहून"] = [lemma, "NOUN", "fem", "sing", "abl"]
    forms[lemma + "ींहून"] = [lemma, "NOUN", "fem", "plur", "abl"]
    forms[lemma + "ीचा"] = [lemma, "NOUN", "fem", "sing", "gen"]
    forms[lemma + "ींचा"] = [lemma, "NOUN", "fem", "plur", "gen"]
    forms[lemma + "ीत"] = [lemma, "NOUN", "fem", "sing", "loc"]
    forms[lemma + "ींत"] = [lemma, "NOUN", "fem", "plur", "loc"]
    forms[lemma + "ी"] = [lemma, "NOUN", "fem", "sing", "voc"]
    forms[lemma + "ींनों"] = [lemma, "NOUN", "fem", "plur", "voc"]
    return forms


def noun_neut(lemma):
    forms = {}
    if lemma[-1] in "ीईेए":
        forms[lemma] = [lemma, "NOUN", "neut", "sing", "nom"]
        forms[lemma[:-1] + "्यें"] = [lemma, "NOUN", "neut", "plur", "nom"]
        forms[lemma + "ीला"] = [lemma, "NOUN", "neut", "sing", "acc"]
        forms[lemma + "्यांना"] = [lemma, "NOUN", "neut", "plur", "acc"]
        forms[lemma + "्यानें"] = [lemma, "NOUN", "neut", "sing", "inst"]
        forms[lemma + "्यांनीं"] = [lemma, "NOUN", "neut", "plur", "inst"]
        forms[lemma + "्याला"] = [lemma, "NOUN", "neut", "sing", "dat"]
        forms[lemma + "्यांला-ना"] = [lemma, "NOUN", "neut", "plur", "dat"]
        forms[lemma + "्याहून"] = [lemma, "NOUN", "neut", "sing", "abl"]
        forms[lemma + "्यांहून"] = [lemma, "NOUN", "neut", "plur", "abl"]
        forms[lemma + "्याचा"] = [lemma, "NOUN", "neut", "sing", "gen"]
        forms[lemma + "्यांचा"] = [lemma, "NOUN", "neut", "plur", "gen"]
        forms[lemma + "्यात"] = [lemma, "NOUN", "neut", "sing", "loc"]
        forms[lemma + "्यांत"] = [lemma, "NOUN", "neut", "plur", "loc"]
        forms[lemma + "्या"] = [lemma, "NOUN", "neut", "sing", "voc"]
        forms[lemma + "्यांनों"] = [lemma, "NOUN", "neut", "plur", "voc"]
    else:
        forms[lemma] = [lemma, "NOUN", "neut", "sing", "nom"]
        forms[lemma] = [lemma, "NOUN", "masc", "plur", "nom"]
        forms[lemma + "ाला"] = [lemma, "NOUN", "masc", "sing", "acc"]
        forms[lemma + "ांना"] = [lemma, "NOUN", "masc", "plur", "acc"]
        forms[lemma + "ानें"] = [lemma, "NOUN", "masc", "sing", "inst"]
        forms[lemma + "ांनीं"] = [lemma, "NOUN", "masc", "plur", "inst"]
        forms[lemma + "ाला"] = [lemma, "NOUN", "masc", "sing", "dat"]
        forms[lemma + "ांना"] = [lemma, "NOUN", "masc", "plur", "dat"]
        forms[lemma + "ाहून"] = [lemma, "NOUN", "masc", "sing", "abl"]
        forms[lemma + "ांहून"] = [lemma, "NOUN", "masc", "plur", "abl"]
        forms[lemma + "ाचा"] = [lemma, "NOUN", "masc", "sing", "gen"]
        forms[lemma + "ांचा"] = [lemma, "NOUN", "masc", "plur", "gen"]
        forms[lemma + "ात"] = [lemma, "NOUN", "masc", "sing", "loc"]
        forms[lemma + "ात"] = [lemma, "NOUN", "masc", "plur", "loc"]
        forms[lemma + "ा"] = [lemma, "NOUN", "masc", "sing", "voc"]
        forms[lemma + "ांनों"] = [lemma, "NOUN", "masc", "plur", "voc"]
    return forms

def adj_masc(lemma):
    forms = {}
    forms[lemma] = [lemma, "ADJ", "masc", "sing", "nom"]
    if lemma[-1] in "ाआ":
        forms[lemma[:-1] + "े"] = [lemma, "ADJ", "masc", "plur", "nom"]
        forms[lemma] = [lemma, "ADJ", "masc", "sing", "acc"]
        forms[lemma + "े"] = [lemma, "ADJ", "masc", "plur", "acc"]
        forms[lemma + "्यानें"] = [lemma, "ADJ", "masc", "sing", "inst"]
        forms[lemma + "्यानीं"] = [lemma, "ADJ", "masc", "plur", "inst"]
        forms[lemma + "्याला"] = [lemma, "ADJ", "masc", "sing", "dat"]
        forms[lemma + "्यांना-ला"] = [lemma, "ADJ", "masc", "plur", "dat"]
        forms[lemma + "्याहून"] = [lemma, "ADJ", "masc", "sing", "abl"]
        forms[lemma + "्यांहून"] = [lemma, "ADJ", "masc", "plur", "abl"]
        forms[lemma + "्याचा"] = [lemma, "ADJ", "masc", "sing", "gen"]
        forms[lemma + "्यांचा"] = [lemma, "ADJ", "masc", "plur", "gen"]
        forms[lemma + "्यात"] = [lemma, "ADJ", "masc", "sing", "loc"]
        forms[lemma + "्यात"] = [lemma, "ADJ", "masc", "plur", "loc"]
        forms[lemma + "्या"] = [lemma, "ADJ", "masc", "sing", "voc"]
        forms[lemma + "्यांनों"] = [lemma, "ADJ", "masc", "plur", "voc"]
    else:
        forms[lemma] = [lemma, "ADJ", "masc", "plur", "nom"]
        forms[lemma + "ाला"] = [lemma, "ADJ", "masc", "sing", "acc"]
        forms[lemma + "ांना"] = [lemma, "ADJ", "masc", "plur", "acc"]
        forms[lemma + "ानें"] = [lemma, "ADJ", "masc", "sing", "inst"]
        forms[lemma + "ांनीं"] = [lemma, "ADJ", "masc", "plur", "inst"]
        forms[lemma + "ाला"] = [lemma, "ADJ", "masc", "sing", "dat"]
        forms[lemma + "ांना"] = [lemma, "ADJ", "masc", "plur", "dat"]
        forms[lemma + "ाहून"] = [lemma, "ADJ", "masc", "sing", "abl"]
        forms[lemma + "ांहून"] = [lemma, "ADJ", "masc", "plur", "abl"]
        forms[lemma + "ाचा"] = [lemma, "ADJ", "masc", "sing", "gen"]
        forms[lemma + "ांचा"] = [lemma, "ADJ", "masc", "plur", "gen"]
        forms[lemma + "ात"] = [lemma, "ADJ", "masc", "sing", "loc"]
        forms[lemma + "ात"] = [lemma, "ADJ", "masc", "plur", "loc"]
        forms[lemma + "ा"] = [lemma, "ADJ", "masc", "sing", "voc"]
        forms[lemma + "ांनों"] = [lemma, "ADJ", "masc", "plur", "voc"]
    return forms


def adj_fem(lemma):
    forms = {}
    forms[lemma] = [lemma, "ADJ", "fem", "sing", "nom"]
    if lemma[-1] in "ईी":
        forms[lemma[:-1] + "्या"] = [lemma, "ADJ", "fem", "plur", "nom"]
        forms[lemma] = [lemma, "ADJ", "fem", "sing", "acc"]
        forms[lemma + "्या"] = [lemma, "ADJ", "fem", "plur", "acc"]
        forms[lemma + "नें"] = [lemma, "ADJ", "fem", "sing", "inst"]
        forms[lemma + "्यांनीं"] = [lemma, "ADJ", "fem", "plur", "inst"]
        forms[lemma + "ला"] = [lemma, "ADJ", "fem", "sing", "dat"]
        forms[lemma + "्यांना-ला"] = [lemma, "ADJ", "fem", "plur", "dat"]
        forms[lemma + "्याहून"] = [lemma, "ADJ", "fem", "sing", "abl"]
        forms[lemma + "्यांहून"] = [lemma, "ADJ", "fem", "plur", "abl"]
        forms[lemma + "ची"] = [lemma, "ADJ", "fem", "sing", "gen"]
        forms[lemma + "्यांचा"] = [lemma, "ADJ", "fem", "plur", "gen"]
        forms[lemma + "ींत"] = [lemma, "ADJ", "fem", "sing", "loc"]
        forms[lemma + "्यांत"] = [lemma, "ADJ", "fem", "plur", "loc"]
        forms[lemma + "े"] = [lemma, "ADJ", "fem", "sing", "voc"]
        forms[lemma + "्यांनों"] = [lemma, "ADJ", "fem", "plur", "voc"]
    else:
        forms[lemma] = [lemma, "ADJ", "fem", "plur", "nom"]
        forms[lemma + "ाला"] = [lemma, "ADJ", "fem", "sing", "acc"]
        forms[lemma + "ांना"] = [lemma, "ADJ", "fem", "plur", "acc"]
        forms[lemma + "ानें"] = [lemma, "ADJ", "fem", "sing", "inst"]
        forms[lemma + "ांनीं"] = [lemma, "ADJ", "fem", "plur", "inst"]
        forms[lemma + "ाला"] = [lemma, "ADJ", "fem", "sing", "dat"]
        forms[lemma + "ांना"] = [lemma, "ADJ", "fem", "plur", "dat"]
        forms[lemma + "ाहून"] = [lemma, "ADJ", "fem", "sing", "abl"]
        forms[lemma + "ांहून"] = [lemma, "ADJ", "fem", "plur", "abl"]
        forms[lemma + "ाचा"] = [lemma, "ADJ", "fem", "sing", "gen"]
        forms[lemma + "ांचा"] = [lemma, "ADJ", "fem", "plur", "gen"]
        forms[lemma + "ात"] = [lemma, "ADJ", "fem", "sing", "loc"]
        forms[lemma + "ात"] = [lemma, "ADJ", "fem", "plur", "loc"]
        forms[lemma + "ा"] = [lemma, "ADJ", "fem", "sing", "voc"]
        forms[lemma + "ांनों"] = [lemma, "ADJ", "fem", "plur", "voc"]
    return forms


def adj_neut(lemma):
    forms = {}
    forms[lemma] = [lemma, "ADJ", "neut", "sing", "nom"]
    if lemma[-1] in "एंें":
        forms[lemma[:-1] + "ी"] = [lemma, "ADJ", "neut", "plur", "nom"]
        forms[lemma] = [lemma, "ADJ", "neut", "sing", "acc"]
        forms[lemma[:-1] + "ी"] = [lemma, "ADJ", "neut", "plur", "acc"]
        forms[lemma + "्यानें"] = [lemma, "ADJ", "neut", "sing", "inst"]
        forms[lemma + "्यानीं"] = [lemma, "ADJ", "neut", "plur", "inst"]
        forms[lemma + "्याला"] = [lemma, "ADJ", "neut", "sing", "dat"]
        forms[lemma + "्यांना-ला"] = [lemma, "ADJ", "neut", "plur", "dat"]
        forms[lemma + "्याहून"] = [lemma, "ADJ", "neut", "sing", "abl"]
        forms[lemma + "्यांहून"] = [lemma, "ADJ", "neut", "plur", "abl"]
        forms[lemma + "्याचा"] = [lemma, "ADJ", "neut", "sing", "gen"]
        forms[lemma + "्यांचा"] = [lemma, "ADJ", "neut", "plur", "gen"]
        forms[lemma + "्यात"] = [lemma, "ADJ", "neut", "sing", "loc"]
        forms[lemma + "्यात"] = [lemma, "ADJ", "neut", "plur", "loc"]
        forms[lemma + "्या"] = [lemma, "ADJ", "neut", "sing", "voc"]
        forms[lemma + "्यांनों"] = [lemma, "ADJ", "neut", "plur", "voc"]
    else:
        forms[lemma] = [lemma, "ADJ", "neut", "plur", "nom"]
        forms[lemma + "ाला"] = [lemma, "ADJ", "neut", "sing", "acc"]
        forms[lemma + "ांना"] = [lemma, "ADJ", "neut", "plur", "acc"]
        forms[lemma + "ानें"] = [lemma, "ADJ", "neut", "sing", "inst"]
        forms[lemma + "ांनीं"] = [lemma, "ADJ", "neut", "plur", "inst"]
        forms[lemma + "ाला"] = [lemma, "ADJ", "neut", "sing", "dat"]
        forms[lemma + "ांना"] = [lemma, "ADJ", "neut", "plur", "dat"]
        forms[lemma + "ाहून"] = [lemma, "ADJ", "neut", "sing", "abl"]
        forms[lemma + "ांहून"] = [lemma, "ADJ", "neut", "plur", "abl"]
        forms[lemma + "ाचा"] = [lemma, "ADJ", "neut", "sing", "gen"]
        forms[lemma + "ांचा"] = [lemma, "ADJ", "neut", "plur", "gen"]
        forms[lemma + "ात"] = [lemma, "ADJ", "neut", "sing", "loc"]
        forms[lemma + "ात"] = [lemma, "ADJ", "neut", "plur", "loc"]
        forms[lemma + "ा"] = [lemma, "ADJ", "neut", "sing", "voc"]
        forms[lemma + "ांनों"] = [lemma, "ADJ", "neut", "plur", "voc"]
    return forms